all:
	gcc ./*.c ../utils/Vector.c ../gui/Menu.c ../gui/TextBox.c ../gui/Button.c ../gui/Window.c ../gui/Camera.c ../gui/Dolly.c  ../SDL_FontCache/*.c -lSDL2 -lSDL_net -lSDL2_ttf -lSDL2_image -o havoc_editor -g -lm
